version: "3"

services:
  db:
    image: mongo:latest
    env_file:
      - ./.env.prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - db_data_container:/data/db
  
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    env_file:
      - ./.env.prod
    ports:
      - 3000:3000
    depends_on:
      - db
    command: npm run start:prod
    volumes:
      - web_images_container:/data/images

volumes:
  db_data_container:
  web_images_container:
